apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      azuremonitor:
        instrumentation_key: INSTRUMENTATION_KEY_PLACEHOLDER
      logging:
        verbosity: normal
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [azuremonitor, logging]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [azuremonitor, logging]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [azuremonitor, logging]