apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kvprovider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: kv-observabilityik
    userAssignedIdentityID: # clusterKeyVaultSecretProviderClientId
    cloudName:
    objects:  |
      array:
        - |
          objectName: CosmosDBEndpoint
          objectType: secret             
        - |
          objectName: CosmosDBKey
          objectType: secret
        - |
          objectName: CosmosDBName
          objectType: secret
    tenantId: # keyVaultTenantId
  secretObjects:
    - data:
        - key: CosmosDBEndpoint
          objectName: CosmosDBEndpoint
        - key: CosmosDBKey
          objectName: CosmosDBKey
        - key: CosmosDBName
          objectName: CosmosDBName
      secretName: devices-api-secrets
      type: Opaque