name: Cherry-pick and Create PR

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Name of the base branch'
        required: true
        type: string
      starting_branch:
        description: 'Name of the starting branch'
        required: true
        type: string
jobs:
  cherry_pick_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.base_branch }}

      - name: Create new branch
        id: create_branch
        run: |
            git checkout -b merge/${{ inputs.base_branch }}

      - name: Cherry-pick latest commit to new branch
        run: |
          git fetch origin
          git cherry-pick origin/${{ inputs.starting_branch }} 

      - name: Push new branch
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ steps.create_branch.outputs.branch }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Cherry-pick latest commit to main"
          branch: ${{ steps.create_branch.outputs.branch }}
          title: "Cherry-pick latest commit to main"
          body: "This PR cherry-picks the latest commit from main to the new branch."
