name: Cherry-pick and Create PR

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Name of the base branch who last commit should be cherry picked and applied to the starting branch"
        required: true
        type: string
      starting_branch:
        description: "Name of the starting branch from which the cherry picked branch of the base should be applied to"
        required: true
        type: string

permissions: write-all

jobs:
  cherry_pick_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.base_branch }}
      - name: Set up Git
        run: |
          git config --local user.email ${{ github.actor }}@users.noreply.github.com
          git config --local user.name ${{ github.actor }}
          git config --global push.autoSetupRemote true

      - name: Cherry-pick latest commit to new branch and push
        run: |
          exists=`git show-ref refs/heads/merge/00-workshop/to/section/05-visualization`
          if [ -n "$exists" ]; then
              echo 'Branch already exist and assumed at right state!'
          else
            git fetch origin
            git checkout -b merge/${{ inputs.base_branch }}/to/${{ inputs.starting_branch }}
            git cherry-pick origin/${{ inputs.starting_branch }}
            git push --set-upstream origin merge/${{ inputs.base_branch }}/to/${{ inputs.starting_branch }}
          fi

      - name: Create Pull Request
        env:
          GH_token: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh auth login --with-token <<< $GH_token
          gh pr create --base ${{ inputs.starting_branch }} --head merge/${{ inputs.base_branch }}/to/${{ inputs.starting_branch }} --title "Merge merge/${{ inputs.base_branch }}/to/${{ inputs.starting_branch }} into ${{ inputs.starting_branch }}" --body "This PR merges merge/${{ inputs.base_branch }}/to/${{ inputs.starting_branch }} into ${{ inputs.starting_branch }}"